#!/usr/bin/env python3
"""
Batch generate multiple chapters from a course configuration file.

This script automates the generation of multiple chapters by reading a course
configuration file that defines all chapters and their variables.

Usage:
    python batch_generate.py <course-config.yaml>
    python batch_generate.py <course-config.yaml> --chapters 1,2,3

Author: compose-textbook-for-k12 skill
Version: 1.0
"""

import sys
import json
import yaml
from pathlib import Path
from datetime import datetime


def load_course_config(config_file):
    """
    Load course configuration from YAML file.
    
    Expected format:
    ```yaml
    course:
      name: "Business Analysis for Smart Retail"
      target_learner: "Grade 10-12 students, Vietnam"
      industry_context: "Vietnam Grocery Retail"
    
    chapters:
      - number: 1
        title: "Business Analyst là gì?"
        core_concepts:
          - "What is a Business Analyst"
          - "Why BA matters in retail"
          - "BA thinking framework introduction"
        opening_story: "Cô Lan and the inventory problem"
        main_case: "Cô Lan's grocery store in District 10"
        role_skill: "Problem identification"
        framework: "Ask → Analyze → Recommend"
        next_topic: "Understanding Your Customers"
      
      - number: 2
        title: "Hiểu khách hàng của bạn"
        ...
    ```
    
    Args:
        config_file: Path to YAML configuration file
        
    Returns:
        dict: Course configuration
    """
    if not Path(config_file).exists():
        return {"error": f"Config file not found: {config_file}"}
    
    try:
        with open(config_file, 'r', encoding='utf-8') as f:
            config = yaml.safe_load(f)
        return config
    except yaml.YAMLError as e:
        return {"error": f"Invalid YAML: {e}"}
    except Exception as e:
        return {"error": f"Error loading config: {e}"}


def generate_chapter_variables(course_config, chapter_config):
    """
    Generate variables dict for a single chapter.
    
    Args:
        course_config: Course-level configuration
        chapter_config: Chapter-specific configuration
        
    Returns:
        dict: Complete variable set for chapter generation
    """
    variables = {
        'COURSE_NAME': course_config.get('name', ''),
        'TARGET_LEARNER': course_config.get('target_learner', ''),
        'INDUSTRY_CONTEXT': course_config.get('industry_context', ''),
        'CHAPTER_NUMBER': str(chapter_config.get('number', '')),
        'CHAPTER_TITLE': chapter_config.get('title', ''),
        'OPENING_STORY_CONTEXT': chapter_config.get('opening_story', ''),
        'MAIN_CASE': chapter_config.get('main_case', ''),
        'ROLE_OR_SKILL': chapter_config.get('role_skill', ''),
        'THINKING_FRAMEWORK': chapter_config.get('framework', ''),
        'NEXT_CHAPTER_TOPIC': chapter_config.get('next_topic', ''),
    }
    
    # Handle core concepts (up to 3)
    core_concepts = chapter_config.get('core_concepts', [])
    for i in range(3):
        key = f'CORE_CONCEPT_{i+1}'
        variables[key] = core_concepts[i] if i < len(core_concepts) else ''
    
    return variables


def save_chapter_variables(variables, output_dir, chapter_number):
    """Save chapter variables to a markdown file."""
    output_file = Path(output_dir) / f"chapter_{chapter_number}_variables.md"
    
    content = f"""# Chapter {chapter_number} Generation Variables

## Course Information
- **Course Name**: {variables['COURSE_NAME']}
- **Target Learner**: {variables['TARGET_LEARNER']}
- **Industry Context**: {variables['INDUSTRY_CONTEXT']}

## Chapter Details
- **Chapter Number**: {variables['CHAPTER_NUMBER']}
- **Chapter Title**: {variables['CHAPTER_TITLE']}

## Core Concepts
1. {variables['CORE_CONCEPT_1']}
2. {variables['CORE_CONCEPT_2']}
3. {variables['CORE_CONCEPT_3']}

## Narrative Elements
- **Opening Story Context**: {variables['OPENING_STORY_CONTEXT']}
- **Main Case**: {variables['MAIN_CASE']}

## BA Framework
- **Role/Skill Focus**: {variables['ROLE_OR_SKILL']}
- **Thinking Framework**: {variables['THINKING_FRAMEWORK']}

## Course Continuity
- **Next Chapter Topic**: {variables['NEXT_CHAPTER_TOPIC']}

---

*Generated by batch_generate.py on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return output_file


def generate_batch_report(config, output_dir, selected_chapters=None):
    """
    Generate a batch processing report.
    
    Args:
        config: Course configuration
        output_dir: Output directory path
        selected_chapters: List of chapter numbers to process (None = all)
        
    Returns:
        dict: Batch processing report
    """
    course = config.get('course', {})
    chapters = config.get('chapters', [])
    
    if selected_chapters:
        chapters = [c for c in chapters if c.get('number') in selected_chapters]
    
    report = {
        'course_name': course.get('name', ''),
        'total_chapters': len(chapters),
        'processed_chapters': [],
        'output_directory': str(output_dir),
        'timestamp': datetime.now().isoformat()
    }
    
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    for chapter_config in chapters:
        chapter_num = chapter_config.get('number', 0)
        
        print(f"\n📖 Processing Chapter {chapter_num}: {chapter_config.get('title', 'Untitled')}")
        
        # Generate variables
        variables = generate_chapter_variables(course, chapter_config)
        
        # Save variables file
        var_file = save_chapter_variables(variables, output_dir, chapter_num)
        print(f"   ✅ Variables saved: {var_file}")
        
        # Generate outline (if generate_outline.py exists)
        outline_script = Path(__file__).parent / "generate_outline.py"
        if outline_script.exists():
            import subprocess
            try:
                result = subprocess.run(
                    ['python3', str(outline_script), str(var_file)],
                    cwd=output_dir,
                    capture_output=True,
                    text=True,
                    timeout=30
                )
                if result.returncode == 0:
                    print(f"   ✅ Outline generated")
                else:
                    print(f"   ⚠️  Outline generation failed: {result.stderr}")
            except Exception as e:
                print(f"   ⚠️  Could not generate outline: {e}")
        
        report['processed_chapters'].append({
            'number': chapter_num,
            'title': chapter_config.get('title', ''),
            'variables_file': str(var_file),
            'status': 'ready'
        })
    
    # Save batch report
    report_file = output_dir / "batch_report.json"
    with open(report_file, 'w', encoding='utf-8') as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
    
    print(f"\n✅ Batch report saved: {report_file}")
    
    return report


def print_batch_summary(report):
    """Print a summary of the batch processing."""
    print("\n" + "="*60)
    print("BATCH GENERATION SUMMARY")
    print("="*60)
    print(f"\nCourse: {report['course_name']}")
    print(f"Total Chapters: {report['total_chapters']}")
    print(f"Output Directory: {report['output_directory']}")
    print(f"\nProcessed Chapters:")
    
    for chapter in report['processed_chapters']:
        print(f"  {chapter['number']}. {chapter['title']} - {chapter['status']}")
    
    print("\n" + "="*60)
    print("NEXT STEPS")
    print("="*60)
    print("\n1. Review generated variable files and outlines")
    print("2. For each chapter, use the master prompt to generate content:")
    print("   - Load references/master-prompt.md")
    print("   - Substitute variables from chapter_X_variables.md")
    print("   - Generate chapter with AI assistant")
    print("\n3. Validate each generated chapter:")
    print("   python scripts/validate_chapter.py output/chapter_X.md")
    print("\n4. Review and iterate based on validation feedback")
    print("="*60 + "\n")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python batch_generate.py <course-config.yaml>")
        print("   or: python batch_generate.py <course-config.yaml> --chapters 1,2,3")
        sys.exit(1)
    
    config_file = sys.argv[1]
    selected_chapters = None
    
    # Parse chapter selection
    if len(sys.argv) > 2 and sys.argv[2] == '--chapters':
        if len(sys.argv) > 3:
            selected_chapters = [int(x.strip()) for x in sys.argv[3].split(',')]
            print(f"\n🎯 Processing selected chapters: {selected_chapters}")
    
    print(f"\n🚀 Loading course configuration: {config_file}")
    
    config = load_course_config(config_file)
    
    if "error" in config:
        print(f"❌ Error: {config['error']}")
        sys.exit(1)
    
    course_name = config.get('course', {}).get('name', 'Unknown Course')
    print(f"✅ Loaded course: {course_name}")
    
    # Create output directory
    output_dir = Path("batch_output")
    
    # Generate batch
    report = generate_batch_report(config, output_dir, selected_chapters)
    
    # Print summary
    print_batch_summary(report)
